
# Gem::Specification for Aska-0.0.5
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: aska
version: !ruby/object:Gem::Version 
  version: 0.0.5
platform: ruby
authors: 
- Ari Lerner
autorequire: 
bindir: bin

date: 2008-07-20 00:00:00 -07:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: The basics of an expert system
email: ari.lerner@citrusbyte.com
executables: []

extensions: []

extra_rdoc_files: 
- CHANGELOG
- lib/aska.rb
- LICENSE
- README
files: 
- CHANGELOG
- lib/aska.rb
- LICENSE
- Manifest
- Rakefile
- README
- spec/rules_spec.rb
- spec/spec_helper.rb
- aska.gemspec
has_rdoc: true
homepage: http://blog.citrusbyte.com
post_install_message: |+
  
        Aska - Expert system basics
        See blog.citrusbyte.com for more details
        *** Ari Lerner @ <ari.lerner@citrusbyte.com> ***
  
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Aska
- --main
- README
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: aska
rubygems_version: 1.2.0
specification_version: 2
summary: The basics of an expert system
test_files: []
