
# Gem::Specification for Aska-0.0.2
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{aska}
  s.version = "0.0.2"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [""]
  s.date = %q{2008-05-27}
  s.description = %q{}
  s.email = %q{}
  s.extra_rdoc_files = ["CHANGELOG", "lib/aska.rb", "LICENSE", "README"]
  s.files = ["aska.gemspec", "CHANGELOG", "lib/aska.rb", "LICENSE", "Manifest", "README", "spec/rules_spec.rb", "spec/spec_helper.rb"]
  s.has_rdoc = true
  s.homepage = %q{}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Aska", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{aska}
  s.rubygems_version = %q{1.0.1}
  s.summary = %q{}
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'echoe'
# Echoe.new('aska')